# Generated by Django 5.2.6 on 2025-10-01 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendamensal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renda',
            old_name='mes',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='renda',
            name='data_recebimento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='renda',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='renda',
            name='tipo',
            field=models.CharField(choices=[('S', 'Salário'), ('F', 'Férias'), ('D', 'Décimo Terceiro'), ('RE', 'Renda extar'), ('O', 'Outras')], default='S', max_length=2),
        ),
    ]
