# Generated by Django 5.2.6 on 2025-10-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendamensal', '0002_rename_mes_renda_nome_renda_data_recebimento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renda',
            old_name='nome',
            new_name='mes',
        ),
    ]
