# Generated by Django 5.2.6 on 2025-10-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rendamensal', '0003_rename_nome_renda_mes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renda',
            name='observacoes',
        ),
    ]
