# Generated by Django 5.2.6 on 2025-11-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequencia', models.CharField(choices=[('D', 'Diária'), ('S', 'Semanal'), ('M', 'Mensal'), ('SM', 'Semestral'), ('A', 'Anual')], default='M', max_length=2)),
                ('tipo', models.CharField(choices=[('GF', 'Gasto Formiga'), ('FX', 'Fixa'), ('V', 'Variável'), ('I', 'Investimento')], default='V', max_length=2)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('pago', models.BooleanField(default=False)),
            ],
        ),
    ]
