# Generated by Django 5.2.6 on 2025-09-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Despesas',
            new_name='Despesa',
        ),
    ]
