# Generated by Django 5.2.6 on 2025-11-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de vencimento'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='mes',
            field=models.CharField(choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março'), ('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], default='01', max_length=60, verbose_name='Mês'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de pagamento'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='frequencia',
            field=models.CharField(choices=[('D', 'Diária'), ('S', 'Semanal'), ('M', 'Mensal'), ('SM', 'Semestral'), ('A', 'Anual')], default='M', max_length=2, verbose_name='Frequência'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da despesa'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pago?'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='tipo',
            field=models.CharField(choices=[('GF', 'Gasto Formiga'), ('FX', 'Fixa'), ('V', 'Variável'), ('I', 'Investimento')], default='V', max_length=2, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
