# Generated by Django 5.2.6 on 2025-12-01 23:53

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0003_despesa_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2000, 1, 1)), django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Data de pagamento'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2000, 1, 1)), django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Data de vencimento'),
        ),
    ]
