# Generated by Django 5.2.6 on 2025-12-03 11:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0004_alter_despesa_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2000, 1, 1))], verbose_name='Data de vencimento'),
        ),
    ]
