# Generated by Django 5.2.6 on 2025-12-08 17:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0005_alter_despesa_data_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='data_vencimento',
            field=models.DateField(default='2025-01-01', validators=[django.core.validators.MinValueValidator(datetime.date(2000, 1, 1)), django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Data de vencimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='despesa',
            name='nome',
            field=models.CharField(default='Despesa', max_length=100, verbose_name='Nome da despesa'),
            preserve_default=False,
        ),
    ]
