# Generated by Django 5.2.6 on 2025-11-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Renda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(blank=True, max_length=60, null=True)),
                ('tipo', models.CharField(choices=[('S', 'Salário'), ('F', 'Férias'), ('D', 'Décimo Terceiro'), ('RE', 'Renda Extra'), ('O', 'Outras')], default='S', max_length=2)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_recebimento', models.DateField()),
            ],
        ),
    ]
