# Generated by Django 5.2.6 on 2025-10-30 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Renda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(blank=True, max_length=60, null=True, verbose_name='Mês')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('tipo', models.CharField(choices=[('S', 'Salario'), ('F', 'Férias'), ('D', 'Décimo Terceiro'), ('RE', 'Renda Extra'), ('O', 'Outras')], default='S', max_length=2, verbose_name='Tipo de Renda')),
                ('data_recebimento', models.DateField(default=datetime.date.today, verbose_name='Data de Recebimento')),
            ],
        ),
    ]
