# Generated by Django 5.2.6 on 2025-11-05 00:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendamensal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renda',
            name='data_recebimento',
            field=models.DateField(verbose_name='Data de recebimento'),
        ),
        migrations.AlterField(
            model_name='renda',
            name='mes',
            field=models.CharField(choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março'), ('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], default=django.utils.timezone.now, max_length=60, verbose_name='Mês'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='renda',
            name='tipo',
            field=models.CharField(choices=[('S', 'Salário'), ('F', 'Férias'), ('D', 'Décimo Terceiro'), ('RE', 'Renda Extra'), ('O', 'Outras')], default='S', max_length=2, verbose_name='Tipo de renda'),
        ),
        migrations.AlterField(
            model_name='renda',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
