# Generated by Django 5.2.6 on 2025-10-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendamensal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renda',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='renda',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='renda',
            name='data_recebimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='renda',
            name='mes',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='renda',
            name='tipo',
            field=models.CharField(choices=[('S', 'Salario'), ('F', 'Férias'), ('D', 'Décimo Terceiro'), ('RE', 'Renda Extra'), ('O', 'Outras')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='renda',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
