# Generated by Django 5.2.6 on 2025-11-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendamensal', '0003_alter_renda_data_recebimento_alter_renda_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renda',
            name='mes',
            field=models.CharField(choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março'), ('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], max_length=60, verbose_name='Mês'),
        ),
    ]
