# Generated by Django 5.2.6 on 2025-12-01 23:33

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendamensal', '0005_renda_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renda',
            name='data_recebimento',
            field=models.DateField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(datetime.date(2000, 1, 1)), django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Data de recebimento'),
        ),
    ]
