# Generated by Django 5.2.6 on 2025-11-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financiamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('01', 'Janeiro'), ('02', 'Fevereiro'), ('03', 'Março'), ('04', 'Abril'), ('05', 'Maio'), ('06', 'Junho'), ('07', 'Julho'), ('08', 'Agosto'), ('09', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], max_length=60, verbose_name='Mês')),
                ('credor', models.CharField(max_length=100, verbose_name='Credor / Instituição')),
                ('tipo', models.CharField(choices=[('IM', 'Imobiliário'), ('VE', 'Veículo'), ('EM', 'Empréstimo Pessoal'), ('CA', 'Cartão de Crédito'), ('OU', 'Outros')], default='OU', max_length=2, verbose_name='Tipo de Financiamento')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('parcelas', models.IntegerField(verbose_name='Número de Parcelas')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Parcela')),
                ('taxa_juros', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taxa de Juros (%)')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('situacao', models.CharField(choices=[('A', 'Em andamento'), ('Q', 'Quitado')], default='A', max_length=1)),
            ],
        ),
    ]
