# Generated by Django 5.2.6 on 2025-11-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financiamento',
            name='data_pagamento',
        ),
        migrations.RemoveField(
            model_name='financiamento',
            name='data_vencimento',
        ),
        migrations.RemoveField(
            model_name='financiamento',
            name='parcelas',
        ),
        migrations.RemoveField(
            model_name='financiamento',
            name='situacao',
        ),
        migrations.AddField(
            model_name='financiamento',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AddField(
            model_name='financiamento',
            name='numero_parcelas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº de Parcelas'),
        ),
        migrations.AddField(
            model_name='financiamento',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
        migrations.AlterField(
            model_name='financiamento',
            name='credor',
            field=models.CharField(max_length=100, verbose_name='Credor'),
        ),
        migrations.AlterField(
            model_name='financiamento',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='financiamento',
            name='tipo',
            field=models.CharField(choices=[('EMP', 'Empréstimo Pessoal'), ('CAR', 'Financiamento de Carro'), ('CASA', 'Financiamento Imobiliário'), ('CARTAO', 'Cartão de Crédito'), ('OUTRO', 'Outro')], default='OUTRO', max_length=10),
        ),
    ]
