# Generated by Django 5.2.6 on 2025-11-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiamentos', '0002_remove_financiamento_data_pagamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financiamento',
            name='numero_parcelas',
        ),
        migrations.RemoveField(
            model_name='financiamento',
            name='taxa_juros',
        ),
        migrations.RemoveField(
            model_name='financiamento',
            name='valor_total',
        ),
        migrations.AlterField(
            model_name='financiamento',
            name='tipo',
            field=models.CharField(choices=[('EMP', 'Empréstimo Pessoal'), ('CAR', 'Financiamento de Carro'), ('CASA', 'Financiamento Imobiliário'), ('CARTAO', 'Cartão de Crédito'), ('OUTRO', 'Outro')], default='OUTRO', max_length=10, verbose_name='Tipo'),
        ),
    ]
