# Generated by Django 5.2.6 on 2025-11-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiamentos', '0003_remove_financiamento_numero_parcelas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financiamento',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento da parcela'),
        ),
        migrations.AddField(
            model_name='financiamento',
            name='numero_parcelas',
            field=models.IntegerField(blank=True, null=True, verbose_name='N° Parcerlas'),
        ),
        migrations.AddField(
            model_name='financiamento',
            name='taxa_juros',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Taxa de Juros (%)'),
        ),
        migrations.AddField(
            model_name='financiamento',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='valor_total'),
        ),
        migrations.AlterField(
            model_name='financiamento',
            name='valor_parcela',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Parcela'),
        ),
    ]
