# Generated by Django 5.2.6 on 2025-11-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financiamentos', '0004_financiamento_data_vencimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financiamento',
            name='numero_parcelas',
        ),
        migrations.RemoveField(
            model_name='financiamento',
            name='taxa_juros',
        ),
        migrations.RemoveField(
            model_name='financiamento',
            name='valor_total',
        ),
    ]
