# Generated by Django 5.2.6 on 2025-11-27 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financiamentos', '0006_financiamento_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financiamento',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='financiamento',
            name='data_inicio',
        ),
    ]
