# Generated by Django 5.2.6 on 2025-12-04 00:04

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiamentos', '0007_remove_financiamento_data_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financiamento',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2000, 1, 1)), django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Data de pagamento'),
        ),
        migrations.AlterField(
            model_name='financiamento',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2000, 1, 1))], verbose_name='Data de vencimento'),
        ),
    ]
