# Generated by Django 5.2.6 on 2025-12-08 17:42

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiamentos', '0008_financiamento_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financiamento',
            name='data_vencimento',
            field=models.DateField(default='2025-01-01', validators=[django.core.validators.MinValueValidator(datetime.date(2000, 1, 1)), django.core.validators.MaxValueValidator(datetime.date.today)], verbose_name='Data de vencimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financiamento',
            name='valor_parcela',
            field=models.DecimalField(decimal_places=2, default='500', max_digits=10, verbose_name='Valor da Parcela'),
            preserve_default=False,
        ),
    ]
