# Generated by Django 5.2.6 on 2025-09-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0002_rename_despesas_despesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='descricao',
        ),
        migrations.AddField(
            model_name='despesa',
            name='frequencia',
            field=models.CharField(choices=[('D', 'Diária'), ('S', 'Semanal'), ('M', 'Mensal'), ('SM', 'Semestral'), ('A', 'Anual')], default='M', max_length=2),
        ),
    ]
