# Generated by Django 5.2.6 on 2025-09-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0003_remove_despesa_categoria_remove_despesa_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
