# Generated by Django 5.2.6 on 2025-09-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0004_despesa_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='descricao',
        ),
        migrations.AddField(
            model_name='despesa',
            name='tipo',
            field=models.CharField(choices=[('GF', 'Gasto Formiga'), ('FX', 'Fixa'), ('V', 'Variável'), ('I', 'Investimento')], default='V', max_length=2),
        ),
    ]
